language: generic
sudo: required
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_USERNAME/patmos-nginx ./nginx
  - docker tag $DOCKER_USERNAME/patmos-nginx registry.heroku.com/$HEROKU_APP_NGINX/web;
  - docker build -t $DOCKER_USERNAME/patmos-gateway ./services/gateway
  - docker tag $DOCKER_USERNAME/patmos-gateway registry.heroku.com/$HEROKU_APP_GATEWAY/web;
  - docker build -t $DOCKER_USERNAME/patmos-site ./ui/site
  - docker tag $DOCKER_USERNAME/patmos-site registry.heroku.com/$HEROKU_APP_SITE/web;
  - docker build -t $DOCKER_USERNAME/patmos-admin ./ui/admin
  - docker tag $DOCKER_USERNAME/patmos-admin registry.heroku.com/$HEROKU_APP_ADMIN/web;

deploy:
  provider: heroku
  api_key:
    secure: "751c3760-1a28-4c6f-b219-dbd8dc57b6f1"
  skip_cleanup: true
  provider: script
  script: 
    # push to dockerhub & heroku 
    docker push $DOCKER_USERNAME/patmos-nginx;
    docker push registry.heroku.com/$HEROKU_APP_NGINX/web;
    heroku container:release web --app $HEROKU_APP_NGINX;
    docker push $DOCKER_USERNAME/patmos-gateway;
    docker push registry.heroku.com/$HEROKU_APP_GATEWAY/web;
    heroku container:release web --app $HEROKU_APP_GATEWAY;
    docker push $DOCKER_USERNAME/patmos-site;
    docker push registry.heroku.com/$HEROKU_APP_SITE/web;
    heroku container:release web --app $HEROKU_APP_SITE;
    docker push $DOCKER_USERNAME/patmos-admin;
    docker push registry.heroku.com/$HEROKU_APP_ADMIN/web;
    heroku container:release web --app $HEROKU_APP_ADMIN;
  on: 
    branch: master 
