version: '3.3'

services:
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports: 
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"
    command: postgres -c max_locks_per_transaction=2000
  maildev:
    image: "djfarrelly/maildev"
    command: bin/maildev --verbose
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data:

