FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install --legacy-peer-deps
RUN npm install react-scripts@3.4.1 -g --silent
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
EXPOSE 3000
CMD ["npm", "start"]